import type { Metadata } from "next";
import { Space_Grotesk, Work_Sans, Geist_Mono } from "next/font/google";
import "./globals.css";

const displayFont = Space_Grotesk({
  variable: "--font-display",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const bodyFont = Work_Sans({
  variable: "--font-body",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const monoFont = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Toaster } from "react-hot-toast";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const themeInitializer = `
    (function() {
      try {
        const root = document.documentElement;
        const storedContrast = localStorage.getItem('drishtiprep-contrast');
        const prefersDark = window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches;
        const prefersMoreContrast = window.matchMedia && window.matchMedia('(prefers-contrast: more)').matches;
        if (prefersDark) root.classList.add('dark');
        if (storedContrast === 'high-contrast' || (!storedContrast && prefersMoreContrast)) root.classList.add('hc');
      } catch (e) {
        // noop
      }
    })();
  `;
  return (
    <html lang="en">
      <head>
        <script dangerouslySetInnerHTML={{ __html: themeInitializer }} />
      </head>
      <body
        className={`${displayFont.variable} ${bodyFont.variable} ${monoFont.variable} antialiased`}
      >
        <a 
          href="#main" 
          className="sr-only focus:not-sr-only focus:absolute focus:top-4 focus:left-4 z-[100] bg-white text-indigo-600 px-4 py-2 font-medium rounded-md shadow-lg outline-none focus:ring-2 focus:ring-indigo-500"
        >
          Skip to content
        </a>
        {children}
        <Toaster position="top-right" />
      </body>
    </html>
  );
}
